# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: flash_semicat

channels:
  - pytorch
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

# TODO: fix env. It was really hard to install flash_attn on some devices.
# It required (python=3.10) torch==2.4.1, torchvision==0.19.1, ninja==1.13.0
# flash_attn==2.7.4.post1 --no-build-isolation --no-cache (probably tmp on different file sys)

dependencies:
  - python=3.10
  - pip>=23
  - pip:
    - torch==2.4.1
    - torchvision==0.19.1
    - torchmetrics==1.8.2
    - lightning==2.6.0
    - hydra-core
    - hydra-optuna-sweeper
    - rich>=13.0
    - hydra-colorlog
    - rootutils
    - pre-commit
    - wandb
    - einops==0.8.1
    - ninja==1.13.0
    - pyarrow==14.0.2
    - datasets==2.19.2
    # - flash_attn==2.7.4.post1 --no-build-isolation --no-cache-dir
