_target_: semicat.models.textsemicat.TextSemicatModule

net:
  _target_: semicat.net.dit.DIT

prior_type: gaussian

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.01

scheduler: null
